kind = "web"
previewPath = "/"
title = "StuManage"
version = "1.0.0"
id = "artifacts/stumanage"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25963

[services.development]
run = "pnpm --filter @workspace/stumanage run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/stumanage", "run", "build" ]
publicDir = "artifacts/stumanage/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25963"
BASE_PATH = "/"
